//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public bool Status { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Comment1 { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
